### ISSUE TITLE
[SPIKE] Caching client connections

### ISSUE THREAD

**Issue by flaviusburca** [mware-solutions/bigconnect#1]
Investigate if current http client caches connections.

**Comment by corneam** [comment]
We are currently using the synchronous com.mashape.unirest.request.BaseRequest#asBinary method which delegates a client resolution to com.mashape.unirest.http.utils.ClientFactory#getHttpClient . This method relies on the Options class which sets all defaults in com.mashape.unirest.http.options.Options#refresh method. When analyzing the code we can see that a PoolingHttpClientConnectionManager is initialized and given to the synchronous client that will be then retrieved on subsequent calls.  Asynchronous client also uses a pooling manager by default.
